name: Build Monorepo

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build All Apps
      run: ./gradlew assembleDebug

    # --- UPLOAD 1: CUSTOMER APP ---
    - name: Upload Customer App
      uses: actions/upload-artifact@v3
      with:
        name: CUSTOMER-APP-APK
        path: apps/customer-app/build/outputs/apk/debug/*.apk

    # --- UPLOAD 2: DRIVER APP ---
    - name: Upload Driver App
      uses: actions/upload-artifact@v3
      with:
        name: DRIVER-APP-APK
        path: apps/driver-app/build/outputs/apk/debug/*.apk
